name: workflow for the api fetching
on: 
  push:
     branches:
        - main

jobs: 
  etl-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: setup-python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
        
      - name: install dependency
        run: pip install -r requirments.txt

      - name: run extract.py
        run: python extract.py

  deploy-job:
    runs-on: ubuntu-latest
    needs: etl-job
    steps:
      - name: checkout-code
        uses: actions/checkout@v2

      - name: deploy job
        run: echo 'doployment is done......'

   